apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: jill-observer-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: jill
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: observer
