apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-list
  name: service-list
  namespace: t23
spec:
  automountServiceAccountToken: false
  serviceAccountName: api-call
  containers:
  - image: nginx
    name: service-list
    command:
    # - /bin/sh
    # - -c
    # - >
    #   'while true; 
    #   do curl -s -k -m 5 -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/t23/pods; 
    #   sleep 10 done'
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
