apiVersion: v1
kind: Pod
metadata:
  name: sysctl-pod
spec:
  nodeName: worker-1
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/somaxconn-allow.json
    sysctls:
    - name: net.core.somaxconn
      value: "1024"
    - name: debug.iotrace
      value: "1"
  containers:
  - name: nginx
    image: nginx:1.23.1
