apiVersion: v1
kind: Pod
metadata:
  name: seccomp-profile
spec:
  nodeName: worker-1
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/mkdir-violation.json
  containers:
  - name: hello
    image: busybox:1.28
    command: ["sh", "-c", "echo 'Hello seccomp!' && sleep 1h"]
    securityContext:
      allowPrivilegeEscalation: false